FROM chuanwen/cowsay:latest

ENTRYPOINT [ "/usr/games/cowsay" ]

CMD [ "#VQV Trybe" ]

# docker image build ./ -t cowsay
# docker container run cowsay
# docker container run cowsay Go Trybe!
# docker container run cowsay -f dragon-and-cow "#VQV TRYBE"
# docker container run cowsay -f moofasa "#VQV TRYBE"
# docker container run cowsay -l