  version: '3'

  services:
    api:
      image: node:16.9.0
      restart: always
      ports:
        - 3001:3001
      volumes: 
        - ./:/app
      working_dir: /app
      command: bash -c "npm install && npm start"