#1
SELECT MAX(SALARY) AS max_salary FROM hr.employees;
#2
SELECT MAX(SALARY) - MIN(SALARY) AS min_to_max FROM hr.employees;
#3
SELECT JOB_ID, AVG(SALARY) AS AVG FROM hr.employees
GROUP BY JOB_ID
ORDER BY AVG;
#4
SELECT SUM(SALARY) AS amount_salaries FROM hr.employees;
#5
SELECT ROUND(MAX(SALARY),2) AS max_salary, ROUND(MIN(SALARY),2) AS min_salary, ROUND(SUM(SALARY),2) AS amount_salaries, ROUND(AVG(SALARY),2) AS avg_salaries FROM hr.employees;
#6
SELECT COUNT(JOB_ID) AS it_employees FROM hr.employees
WHERE JOB_ID = 'IT_PROG';
#7
SELECT JOB_ID, SUM(SALARY) AS SUM FROM hr.employees
GROUP BY JOB_ID;
#8
SELECT JOB_ID, SUM(SALARY) AS SUM FROM hr.employees
WHERE JOB_ID = 'IT_PROG';
#9
SELECT JOB_ID, ROUND(AVG(SALARY),2) AS AVG FROM hr.employees
WHERE JOB_ID <> 'IT_PROG'
GROUP BY JOB_ID
ORDER BY AVG; 
#10
SELECT * FROM hr.employees;
SELECT DEPARTMENT_ID, COUNT(department_id) AS QTY, ROUND(AVG(SALARY),2) AS AVG 
FROM hr.employees
GROUP BY department_id
HAVING QTY > 10;
#11
SELECT REPLACE(PHONE_NUMBER, '515', 777) FROM hr.employees;
SET SQL_SAFE_UPDATES=0;
UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';
SELECT * FROM hr.employees
WHERE PHONE_NUMBER LIKE '777%';
#12
SELECT * FROM hr.employees
WHERE CHAR_LENGTH(FIRST_NAME) >= 8;
#13
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;
#14
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;
#15
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;
#16
SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) FROM hr.employees;
#17
SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE HIRE_DATE BETWEEN '1987-07-01' AND '1987-07-31';
#18
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) AS 'TIME' FROM hr.employees;